/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:bf624cac-5e1e-4346-9e9e-bff72da443d4",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_SPL3Xw7RY",
    "aws_user_pools_web_client_id": "7viit3h3hukl29199qaaps6t8j",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://4pcs4aeqzja2jkbgm6vefni6by.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yoni2lbrgrb6hatbc5ralpu2hy"
};


export default awsmobile;
